# Generated by Django 5.2.6 on 2025-11-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_rating',
        ),
    ]
