# Generated by Django 5.2.6 on 2025-11-16 23:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profileviewcount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profileviewcount',
            new_name='profileview',
        ),
    ]
