# Generated by Django 5.2.6 on 2025-11-17 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_profileviewcount_profileview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profileview',
        ),
    ]
