# Generated by Django 5.2.6 on 2025-11-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_profileview'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
